java -jar ./node_modules/google-closure-compiler/compiler.jar \
  --js='src/**.js' \
  --js='node_modules/google-closure-library/closure/goog/**.js' \
  --js_output_file='build/bundle.min.js' \
  --module_resolution=NODE \
  --language_in=ES6 \
  --language_out=ES3 \
  --dependency_mode=STRICT \
  --entry_point=src/index \
  --isolation_mode=IIFE \
  --compilation_level=ADVANCED \
  --warning_level=VERBOSE